modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/5head/issues"
license="MIT"

[[mods]]
modId="fivehead"
version="${file.jarVersion}"
displayName="5Head"
displayURL="https://www.curseforge.com/minecraft/mc-mods/5head"
authors="Mrbysco"
description='''
A mod for big brain people
'''