modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/5head/issues"
license="MIT"

[[mods]]
modId="fivehead"
version="${file.jarVersion}"
displayName="5Head"
displayURL="https://www.curseforge.com/minecraft/mc-mods/5head"
authors="Mrbysco"
description='''
A mod for big brain people
'''
[[dependencies.fivehead]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.fivehead]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"