modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/5head/issues"
license="MIT"

[[mods]]
modId="fivehead"
version="${file.jarVersion}"
displayName="5Head"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fivehead"
authors="Mrbysco"
description='''
A mod for big brain people
'''
[[dependencies.fivehead]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.fivehead]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "fivehead.mixins.json"