modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/5head/issues"
license="MIT"

[[mods]]
modId="fivehead"
version="${file.jarVersion}"
displayName="5Head"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fivehead"
authors="Mrbysco"
description='''
A mod for big brain people
'''
[[dependencies.fivehead]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.7,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.fivehead]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.7.0-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="fivehead.mixins.json"